### ISSUE TITLE
Release new version of the SemanticData

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#346]
# Release new version
 
## Packages to be released

- [ ] `Common`
- [ ] `Configuration`
- [ ] `DataDiscovery`
- [ ] `Networking`
- [x] `SemanticData`

## Tasks to be done

- [x] Update version information for all published assemblies (Model.t4), 
- [x] Prepare an example if applicable
- [x] Update Readme files
- [x] Update the release documentation (ReleaseNoteTemplate)
- [ ] Prepare NuGet packages if applicable
- [ ] Create release front page
   - [x] Getting Started
   - [x] Version information
- [x] Prepare binary deliverables and publish the installation package
- [x] Update and publish the code help documentation
- [x] Publish release
- [x] Update the project front page
