### ISSUE TITLE
SemanticData Final release

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#351]
# Release new version
 
## Packages to be released

- [ ] `Configuration`
- [ ] `DataDiscovery`
- [ ] `Networking`
- [X] `SemanticData`

## Tasks to be done

- [x] Update version information for all published assemblies (Model.t4), 
- [x] Prepare an example if applicable
- [x] Update Readme files
- [x] Prepare and publish NuGet packages if applicable. Replace project references by packages.
- [x] Create release front page
   - [x] Getting Started
   - [x] Version information
- [x] Prepare binary deliverables and publish the installation package
- [x] Update and publish the code help documentation
- [x] Publish release
- [ ] Update the repository front page
