### ISSUE TITLE
New release: Azure Gateway Implementation 1.0 Repository 6.1.2

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#492]
# Release new version

- Azure Gateway Implementation 1.0 
- Repository 6.1.2
 
## Packages to be released

- [x] `Common`
- [x] `Configuration`
- [x] `DataDiscovery`
- [x] `Networking`
- [x] `SemanticData`

## Tasks to be done

- [x] Update version information for all published assemblies (Model.t4), 
- [x] Prepare an example if applicable
- [x] Update Readme files
- [x] Update the release documentation (ReleaseNoteTemplate)
- [x] Prepare NuGet packages if applicable
- [x] Create release front page
   - [x] Getting Started
   - [x] Version information
- [x] Prepare binary deliverables and publish the installation package
- [x] Update and publish the code help documentation
- [x] Publish release
- [x] Update the project front page

**Comment by mpostol** [comment]
Continue in mpostol/cas.internal#80
