### ISSUE TITLE
SemanticData - create NuGet packages and create release 6.3.3-Golf

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#499]
# Release 6.3.3-Golf
 
## Packages to be released

- [x] `Common.Infrastructure`
- [x] `SemanticData`
  - [x] `BuildingErrorsHandling`
  - [x] `UANodeSetValidation`
  - [x] `UAModelDesignExport`

## Tasks to be done

- [x] Update version information for all published assemblies (Model.t4),
- [ ] review nuspec files
  - [x] `Common.Infrastructure`
  - [x] `SemanticData`
    - [x] `BuildingErrorsHandling`
    - [x] `UANodeSetValidation`
    - [x] `UAModelDesignExport`
- [x] review assembly names
  - [x] `Common.Infrastructure`
  - [ ] `SemanticData`
    - [ ] `BuildingErrorsHandling`
    - [ ] `UANodeSetValidation`
    - [ ] `UAModelDesignExport`
- [x] Create release front page
   - [x] Title: ModelDesign Export Release Candidate
   - [x] Version information: 6.3.3-Golf
- [x] Create and switch to branch Release6.3.3-Golf
- [x] Prepare NuGet packages and remove project dependencies
  - [x] `Common.Infrastructure`
  - [x] `SemanticData`
    - [x] `BuildingErrorsHandling`
    - [x] `UANodeSetValidation`
    - [x] `UAModelDesignExport`
- [ ] Update and publish the code help documentation
- [x] Publish release
- [ ] Update the project front page
- [ ] Close all no longer valid issues and milestone
