### ISSUE TITLE
Create release 6.2.1+

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#500]
# Release new version
 
## Packages to be released

- [ ] `Common`
- [ ] `Configuration`
- [ ] `DataDiscovery`
- [ ] `Networking`
- [ ] `SemanticData`

## Tasks to be done

- [ ] Update version information for all published assemblies (Model.t4), 
- [ ] Prepare an example if applicable
- [ ] Update Readme files
- [ ] Update the release documentation (ReleaseNoteTemplate)
- [ ] Prepare NuGet packages if applicable
- [ ] Create release front page
   - [ ] Getting Started
   - [ ] Version information
- [ ] Prepare binary deliverables and publish the installation package
- [ ] Update and publish the code help documentation
- [ ] Publish release
- [ ] Update the project front page
