### ISSUE TITLE
ADI model from Embedded example import fails

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#509]
ADI model from Embedded example import fails because DI namespace is selected and ) nodes are selected.

**Comment by mpostol** [comment]
Further development will be conducted on the branch <https://github.com/mpostol/OPC-UA-OOI/tree/SemanticData-6.1.3>

**Comment by mpostol** [comment]
## Tasks

- [  ] possibility to open ModelDesign file by ASMD
- [ ] possibility to import NodeSet file
- [ ] possibility to convert NodeSet to ModelDesign
- [  ] possibility to open generated ModelDesign file by ASMD
- [ ] possibility to compile ModelDesign and generate NodeSet file (round trip test)
- [ ] validation against the schema and compliance with the specification (Part 3 and Part 5) of the NodeSet file
- [ ] correct generation of the model documentation in MS Word format
- [ ] correct generation of website content with the model documentation

**Comment by mpostol** [comment]
###  possibility to import NodeSet file

- appropriate namespace must be selected - now DI is validated
- validation ADI causes some unexpected problems (must be investigated)

**Comment by mpostol** [comment]
## validation ADI causes some unexpected problems (must be investigated)

Exception while comparing BrowseName. An exception is thrown by the different syntax of the BrowseName

- `1:TransitionNumber vs TransitionNumber`
- `1:StateNumber vs StateNumber`

## UANodeSet schema: 

From `http://opcfoundation.org/UA/2011/03/UANodeSet.xsd`

```xml
  <xs:complexType name="UANode">
    ...
    <xs:attribute name="BrowseName" type="QualifiedName" use="required"></xs:attribute>
    ....
  </xs:complexType>

  <xs:simpleType name="QualifiedName">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

```

## [OPC Part 3](https://reference.opcfoundation.org/v104/Core/docs/Part3/8.3/)

| Name           | Type   | Description                                                                                                                                                                                                                            |
| -------------- | ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| namespaceIndex | UInt16 | Index that identifies the namespace that defines the name. This index is the index of that namespace in the local Server’s NamespaceArray.The Client may read the NamespaceArray Variable to access the string value of the namespace. |
| name           | String | The text portion of the QualifiedName.                                                                                                                                                                                                 |

## OPC Part 6

### [Annex F (normative) Information Model XML Schema](https://reference.opcfoundation.org/v104/Core/docs/Part6/F.1/)

The XML Schema released with this version of the standards can be found here:

<http://www.opcfoundation.org/UA/schemas/1.04/UANodeSet.xsd>

NOTE The latest file that is compatible with this version of the standards can be found here:

<http://opcfoundation.org/UA/2011/03/UANodeSet.xsd>

### [F.3 UANode](https://reference.opcfoundation.org/v104/Core/docs/Part6/F.3/)

| Element | Type | Description |
| ------- | ---- | ----------- |
BrowseName| QualifiedName| A QualifiedName serialized as a String with the form: `<namespace index>:<name>`Where the NamespaceIndex refers to the NamespaceUris table.

**Comment by mpostol** [comment]
### [5.3.1.14 QualifiedName](https://reference.opcfoundation.org/v104/Core/docs/Part6/5.3.1/#5.3.1.14)

There is another interesting OPC UA specyfication entry point sugested by @jouniaro. It describes the syntax of the Qualified name encoded as the XML element on the wire to transfer it between the OPC UA applications:

A `QualifiedName` value is encoded as an xs:complexType with the following XML schema:

```XML
  <xs:complexType name="QualifiedName">
    <xs:sequence>
      <xs:element name="NamespaceIndex" type="xs:int" minOccurs="0" />
      <xs:element name="Name" type="xs:string" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
```

### Note

- `<minOccurs>` - The `<minOccurs>` indicator specifies the minimum number of times an element can occur. It mens that the following snipped is valid against the schema:

```XML
  <QualifiedName>
  </QualifiedName>
```

**Comment by mpostol** [comment]
Some more snippets from the [OPC UA Address Space Interchange XML](https://www.researchgate.net/publication/334259707_OPC_UA_Address_Space_Interchange_XML) related to BrowseName:

`The BrowseName of a Property is always unique in the context of a node. Any node is not permitted to refer to two Variables using references of the HasProperty type having the same BrowseName.`

`If the DataVariable is used as instance declaration all nodes referenced with hierarchical references in the forward direction shall have unique BrowseNames in the context of this DataVariable.`

```TXT
`MethodDeclarationId
This attribute may be specified for a Method node that is a target of a HasComponent reference from a single Object node. It is the NodeId of the UAMethod with the same BrowseName contained in the TypeDefinition associated with the Object node. If the TypeDefinition overrides a Method inherited from a base ObjectType, this attribute shall reference the Method node in the subtype.
```

```TXT
A unique name for the data type encoded using the syntax described in the section QualifiedName. This field is only specified for nested DataTypeDefinitions. The BrowseName of the DataType node is used otherwise
```

```TXT
UAReferenceType

The inherited BrowseName attribute is used to specify the meaning of the ReferenceType as seen from the source node. For example, the ReferenceType with the BrowseName “Contains” is used in References which specify that the source node contains the target node. The inherited DisplayName attribute contains a translation of the BrowseName.

The BrowseName of a ReferenceType shall be unique in a server. It is not allowed that two different ReferenceTypes have the same BrowseName.
```
```TXT
BrowseName
Nodes have a BrowseName attribute that is used as a non-localized human-readable name when browsing the Address Space to create paths out of BrowseNames. The TranslateBrowsePathsToNodeIds service can be used to follow a path constructed of BrowseNames.
A BrowseName should never be used to display the name of a node. The DisplayName should be used instead for this purpose.
Unlike NodeId, the BrowseName cannot be used to unambiguously identify a node. Different nodes may have the same BrowseName.
The section BrowseName defines the structure of the BrowseName. It contains a namespace and a string. The namespace is provided to make the BrowseName unique in some cases in the context of a Node (e.g. Properties of a Node) although not unique in the context of a server Address Space. If different organizations define BrowseNames for Properties, the namespace of the BrowseName provided by the organization makes the BrowseName unique, although different organizations may use the same string having a slightly different meaning.
Servers may often choose to use the same namespace for the NodeId and the BrowseName. However, if they want to provide a standard Property, its BrowseName shall have the namespace of the standard body although the namespace of the NodeId reflects something else, for example, the local server.
It is recommended that standard bodies defining standard type use their namespace for the NodeId of the TypeDefinitionNode as well as for the BrowseName of the TypeDefinitionNode.
The string-part of the BrowseName is case sensitive. That is, Clients shall consider it case sensitive. Servers are allowed to handle BrowseNames passed in service requests as case insensitive. Examples are the TranslateBrowsePathsToNodeIds service or Event filter.
```

```TXT
SymbolicName
A symbolic name for the node that can be used as a class/field name by design tools to enhance auto-generated code. It should only be specified if the BrowseName cannot be used for this purpose. This field is not used directly to instantiate Address Space and is intended for use by design tools. Only letters, digits, or the underscore (‘_’) are permitted. This attribute is not exposed in the Address Space.
```

**Comment by mpostol** [comment]
The current result of ValidateAndExportModel with default exporter

```TXT
Test Name:	ADITest
Test Outcome:	Passed
Result StandardOutput:	
Debug Trace:
Trace: Verbose, Error Focus:Diagnostic, ErrorID: P0-0003010000 Info: It is diagnostic information Entering IAddressSpaceContext.ValidateAndExportModel - starting for the http://opcfoundation.org/UA/ADI/ namespace.
Trace: Verbose, Error Focus:Diagnostic, ErrorID: P0-0003010000 Info: It is diagnostic information AddressSpaceContext.ValidateAndExportModel - selected 41 nodes to be added to the model.
Trace: Information, Error Focus:NodeClass, ErrorID: P3-0502020001 Info: NodeId is not defined. References to node with NodeId: ns=2;i=12386 is omitted during the import.
Trace: Information, Error Focus:NodeClass, ErrorID: P3-0502020001 Info: NodeId is not defined. References to node with NodeId: ns=2;i=12386 is omitted during the import.
Trace: Information, Error Focus:NodeClass, ErrorID: P3-0502020001 Info: NodeId is not defined. References to node with NodeId: ns=2;i=12386 is omitted during the import.
Trace: Verbose, Error Focus:Diagnostic, ErrorID: P0-0003010000 Info: It is diagnostic information Finishing Validator.ValidateExportModel - the model contains 41 nodes.

```

**Comment by mpostol** [comment]
## Decision

- close this issue
- the problem related to the BrowseName fork to #538 
- for ADI model testing add the current model to the #516
