### ISSUE TITLE
Use Common XML serializer to manage xml documents

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#589]
## Describe the bug

In many places `XmlSerializer` is used. The common implementation is located in the `UAOOI.Common.Infrastructure`

## Expected behavior

Refer to the existing implementation of the serialize/deserialize functionality

## Tasks list

- [x] review the code to find `XmlSerializer`
- [x] replace it with appropriate reference
- [x] improve sterilization to avoid many definitions of the namespace
