### ISSUE TITLE
ModelDesign.GetNamespaces() must use XML stuff

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#621]
## Describe the bug

the method uses Prefix to create `XmlQualifiedName`

## To Reproduce

Always

## Expected behavior

The method must use `XmlPrefix`

## Tasks

- [x] Fix problem in the code
- [x] Create new NugetPackage
- [x] Test it using ASMD
