### ISSUE TITLE
Remove UT bugs of UANodeContextUnitTest

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#675]
## Describe the bug

There are problems with the UT in the UANodeContextUnitTest tests

## To Reproduce

1. Go to 'UANodeContextUnitTest' class
2. Run all tests
3. 4. See errors

## Tasks

- [ ] remove UT errors in the class `UANodeContextUnitTest`
- [ ] test all classes
- [ ] fix all issues.
